import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "./navbar/page";
import TopBar from "./topbar/page";
import "./globals.css";
 
import Footer from "./footer/page";

 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TopBar />
        <Navbar />
        {children}
           <Footer/>

      </body>
    </html>
  );
}
 
 